// GENERATED by tools/generate_914_dbc.py -- do not edit.
//
// Broadcast in SchemaId (0x1FFFFFFE) so a consumer can tell whether the stream it is decoding
// matches the DBC it has loaded. Regenerate whenever the map changes; the hash is derived from
// the map's structure, so it cannot be forgotten the way a hand-maintained version can.
#ifndef SCHEMA_ID_H
#define SCHEMA_ID_H

#define SCHEMA_MAJOR 0x04u
#define SCHEMA_MINOR 0x02u
#define SCHEMA_HASH  0x09EB175Au

#endif // SCHEMA_ID_H
